[tool.poetry]
name = "mango-habanero-be"
version = "0.1.0"
description = "Backend for Mango Habanero."
authors = ["Mango Habanero <main@mango-habanero.dev>"]
readme = "README.md"
packages = [{include = "mango_habanero_be"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.2"
uvicorn = "^0.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
