name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Setup python and install dependencies.
        uses: ./.github/actions/python

      - name: Determine next version.
        id: version
        run: echo ::set-output name=version::$(semantic-release version --print)

      - name: Setup QEMU.
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx.
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push docker image.
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: mangohabanero/be:latest, mangohabanero/be:${{ steps.version.outputs.version }}

  release:
    runs-on: ubuntu-latest
    needs: [ setup-and-build ]
    environment: production
    permissions:
      contents: write
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for full history.

      - name: Setup python and install dependencies.
        uses: ./.github/actions/python

      - name: Python semantic release.
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
