name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Setup QEMU.
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx.
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker content trust.
        run: export DOCKER_CONTENT_TRUST=1

      - name: Build and push Docker image.
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mangohabanero/be:latest, mangohabanero/be:${{ github.event.release.tag }}
          cache-from: type=registry,ref=mangohabanero/be:cache
          cache-to: type=inline
